### ISSUE TITLE
请问这个程序是包括了以前的地图版本吗？有些地方我在百度或者谷歌地图上搜索不到，使用该程序还是会生成经纬度。如果包括了以前的地图，请问您是怎么获取的之前版本的地图呢？如果没有包括以前旧版本的地图，想请问下搜索地址返回的经纬度是区县所处的中心店的经纬度还是什么呢？另外，还想问下这个程序一天最多可以返回多少条地址的经纬度呀？谢谢~

### ISSUE THREAD

**Issue by heyang95** [sjfkai/mapLocation#19]

**Comment by sjfkai** [comment]
你好

1.  该程序完全依赖于谷歌和百度的开放API。并没有版本区分。至于你说为什么在百度和谷歌地图搜不到，这个问题我咨询过百度的客服，得到的回复是该API使用的数据库与百度地图使用的数据库还是有差别的，所以不能保证结果完全一致。
2. 是否是区县的中心点我不太确定，如果需要知道可以咨询对应api的客服，我个人感觉是区县政府所在位置。
3. 一天全网共享限额是30万次（百度API个人认证用户的请求上限）

百度API文档： https://lbsyun.baidu.com/index.php?title=webapi/guide/webservice-geocoding
