### ISSUE TITLE
提醒一下

### ISSUE THREAD

**Issue by freedomlang** [sjfkai/mapLocation#2]
你的ak 在源码里面

**Comment by sjfkai** [comment]
@freedomlang 知道的，不过已经设置了域名限制 没关系的。谢谢哈

**Comment by freedomlang** [comment]
在demo 看到具体的请求，可以看到具体限制>_<！建议demo 做成配置相关ak 以及相关限制

**Comment by sjfkai** [comment]
这个我也想过，不过大部分人只是来用功能的，要求他们申请百度账号太麻烦了。所以就用我的ak了。ak只允许了一个服务，所以也没啥风险。
