### ISSUE TITLE
更换Key

### ISSUE THREAD

**Issue by CHENZUDE** [sjfkai/mapLocation#44]
您百度的key运行报错
https://api.map.baidu.com/geocoding/v3/?address=郝穴镇中央半岛16号商铺&output=json&ak=gQsCAgCrWsuN99ggSIjGn5nO&callback=showLocation5
{"status":220,"message":"APP Referer校验失败"}

**Comment by CHENZUDE** [comment]
我把项目拉到本地跑，更换了我自己的key也提示配额用完

**Comment by CHENZUDE** [comment]
我把项目拉到本地，换上我自己的key，但是更换key以后项目使用的接口就从api.map.baidu.com/geocoding/v3变成了api.map.baidu.com/geocoder/v2，而百度已经弃用geocoder/v2接口

**Comment by sjfkai** [comment]
为了提高总额度，我这边v2 v3都在用。但是最新的api key 不支持v2接口。 可以尝试修改一下下面代码 把两个url都改成v3
https://github.com/sjfkai/mapLocation/blob/master/src/utils/geocoder.js#L17

另外需要清理一下l ocalstorage 数据

**Comment by CHENZUDE** [comment]
function getUrl() {
  if (!localStorage) {
    return 'https://api.map.baidu.com/geocoding/v3/'
  }
  let url = localStorage.getItem(urlCacheKey)
  localStorage.clear()
  if (!url) {
    url = Math.random() < 0.5
      ? 'https://api.map.baidu.com/geocoding/v3/'
      : 'https://api.map.baidu.com/geocoding/v3/'
    localStorage.setItem(urlCacheKey, url)
  }
  return url
}

我改成这样请求还是用的v2

**Comment by sjfkai** [comment]
改成：
```js
function getUrl() {
  return 'https://api.map.baidu.com/geocoding/v3/'
}
```

**Comment by CHENZUDE** [comment]
ok，解决了，谢谢
